export const writings = [
  {
    slug: 'backend-performance',
    title: 'why your backend is slow and what to do about it',
    date: 'jan 5, 2026',
    readTime: '5 min read',
    tag: 'backend systems',
    summary: 'small backend choices can quietly add latency. a practical look at databases, queues, blocking work, and observability.',
    href: 'https://medium.com/coffeed/why-your-backend-is-slow-and-what-to-do-about-it-d008d7ae9566',
    image: 'https://media.coffeed.one/why-your-backend-is-slow-and-what-to-do-about-it-d008d7ae9566/4fc5f036d8cc56748265.png',
    blocks: [
      { type: 'paragraph', text: `most people expect web apps to respond instantly. even small delays change how users feel. attention drops. frustration grows. trust in the system weakens.` },
      { type: 'heading', level: 3, text: 'where backend fails' },
      { type: 'paragraph', text: `that is why backend performance matters. the backend controls how fast data moves, how long requests wait, and how smooth the experience feels. a slow backend makes even a well-designed interface feel broken.` },
      { type: 'paragraph', text: `whether you are building a new system or improving an existing one, here are some common causes of slowness and how to address them.` },
      { type: 'heading', level: 2, text: '1. third-party integrations' },
      { type: 'paragraph', text: `since we don’t create software from scratch, we use existing libraries, packages, and frameworks in our platforms to help with our app functionalities.` },
      { type: 'paragraph', text: `the mistake is choosing packages only based on features. you also need to consider size, maintenance, and performance.` },
      { type: 'paragraph', text: `for example, you might need to resize and compress images.` },
      { type: 'list', items: [
        'option a: a library that supports every format, filters, and transformations, but adds 40 mb to your container and uses a lot of memory.',
        'option b: a simpler library that only resizes and compresses, adds 4 mb, and is actively maintained.',
      ] },
      { type: 'paragraph', text: `if your use case is only resizing profile images, option b is the better choice. less memory, smaller builds, faster cold starts.` },
      { type: 'paragraph', text: `another example is logging. a logging package that supports cloud sync, dashboards, alerts, and metrics may look attractive. but if you only need file logs and console output, that extra machinery slows every request. a minimal logger often performs better and is easier to maintain.` },
      { type: 'heading', level: 2, text: '2. database' },
      { type: 'paragraph', text: `inefficient queries are the silent killers of performance in applications.` },
      { type: 'paragraph', text: `every idea for logic or query writing starts with: “am i implementing the operation correctly?” (getting the right response and modifications). but above this, we need to add one more layer immediately, once that is done: “how efficient is it?”` },
      { type: 'paragraph', text: `to keep the data flowing fast, we need to minimise operations. consider the following techniques:` },
      { type: 'heading', level: 3, text: 'the n+1 problem' },
      { type: 'paragraph', text: `it happens when we fetch a list of items from database and then loop through them to fetch related data for each item. simply put, it’s like going to the grocery store separately for every single egg you need. instead, use eager loading or joins to grab everything in one trip.` },
      { type: 'heading', level: 3, text: 'indexing' },
      { type: 'paragraph', text: `searching for a specific chapter without an index would require more time. that is exactly what your database does when you don’t index your columns. proper indexing is the map your database needs to find data instantly.` },
      { type: 'heading', level: 3, text: 'selective fetching' },
      { type: 'paragraph', text: `stop selecting ALL. if you only need a user’s name, don’t fetch their entire bio, address, and profile history. minimise the data payload to exactly what you need for that specific scenario.` },
      { type: 'heading', level: 3, text: 'connection pooling' },
      { type: 'paragraph', text: `opening and closing database connections is expensive. use a connection pool so requests reuse connections instead of creating new ones.` },
      { type: 'paragraph', text: `this reduces latency and lowers pressure on the database.` },
      { type: 'heading', level: 3, text: 'caching' },
      { type: 'paragraph', text: `sometimes the fastest operation is no operation. if the same data is requested again and again, cache it.` },
      { type: 'paragraph', text: 'examples:' },
      { type: 'list', items: ['user profiles and settings', 'feature flags', 'expensive reports', 'dashboards'] },
      { type: 'paragraph', text: `use in-memory caches like redis or memcached, http caching for public responses, and simple in-process caching where appropriate.` },
      { type: 'heading', level: 2, text: '3. fire and forgot' },
      { type: 'paragraph', text: `in our minds, we starts plan out the flow sequentially, one component after another. but in execution, that is not necessarily the case.` },
      { type: 'paragraph', text: `assume you are in a restaurant. you ordered a main dish and started eating. later, you felt you needed a side dish, so you ordered it. you wouldn’t pause eating your main dish just to wait for the side dish to arrive. you know you don’t need it to finish your current bite.` },
      { type: 'paragraph', text: `find the functions and code blocks in your scripts that do not give any immediate benefit to the user. the flow of the application shouldn’t have to await for these functions to complete. queues and background tasks are very helpful for this scenario.` },
      { type: 'paragraph', text: `for example, when a user signs up,` },
      { type: 'heading', level: 3, text: 'bad:' },
      { type: 'code', lines: ['create_user()', 'send_welcome_email()', 'return response'] },
      { type: 'heading', level: 3, text: 'good:' },
      { type: 'code', lines: ['create_user()', 'enqueue_email_job()', 'return response'] },
      { type: 'paragraph', text: `the user sees success immediately while the email is sent in the background.` },
      { type: 'paragraph', text: `the same applies to analytics events. page views and button clicks should be queued and processed later instead of slowing down the main request.` },
      { type: 'heading', level: 2, text: '4. blocking functions' },
      { type: 'paragraph', text: `every synchronous function call (where the program pauses at that line until the function completes) affects the throughput incredibly, especially in applications used by multiple users. it makes the entire system slow down horribly.` },
      { type: 'paragraph', text: `to fix this, we need to find and remove these bottlenecks,` },
      { type: 'heading', level: 3, text: 'go async' },
      { type: 'paragraph', text: `get rid of blocking snippets throughout the code base by turning them into asynchronous function calls (where the program kicks off the work and immediately moves on to the next line).` },
      { type: 'heading', level: 3, text: 'use worker threads' },
      { type: 'paragraph', text: `not every piece of code can be converted into asynchronous; some might be cpu-bound executions or third-party libraries without async functionality.` },
      { type: 'paragraph', text: `for such components, execute them in a separate thread (offloading the heavy lifting to a different cpu core) rather than the main web server thread. this makes the main application thread keep running without waiting, thus solving the blocking problem.` },
      { type: 'heading', level: 2, text: '5. slow external services' },
      { type: 'paragraph', text: `even if your own system is fast, a slow dependency can make you slow.` },
      { type: 'paragraph', text: 'protect yourself with:' },
      { type: 'list', items: ['timeouts', 'circuit breakers', 'fallbacks'] },
      { type: 'paragraph', text: `if a service is slow, return a partial response instead of blocking the whole request.` },
      { type: 'heading', level: 2, text: '6. rate limiting' },
      { type: 'paragraph', text: `without limits, one noisy client or one bug can overwhelm the system.` },
      { type: 'paragraph', text: `rate limiting protects the backend and keeps performance stable under load.` },
      { type: 'paragraph', text: `backpressure ensures the system degrades gracefully instead of collapsing.` },
      { type: 'heading', level: 2, text: '7. observability' },
      { type: 'paragraph', text: `you cannot fix what you cannot see.` },
      { type: 'paragraph', text: 'add:' },
      { type: 'list', items: ['structured logs', 'request tracing', 'latency and error metrics'] },
      { type: 'paragraph', text: `this helps you find real bottlenecks instead of guessing.` },
      { type: 'heading', level: 2, text: 'conclusion' },
      { type: 'paragraph', text: `backend optimization is not just about saving milliseconds off a request to the server. it is about empathy for the users, respecting their time and attention.` },
      { type: 'paragraph', text: `a fast system feels calm and reliable. a slow system creates friction and doubt.` },
      { type: 'paragraph', text: `performance problems rarely show up in small tests. they show up when real users arrive, when traffic spikes, when data grows, and when systems age.` },
      { type: 'paragraph', text: `use tracing and profiling tools to understand where time is actually being spent. optimize the slow parts, not the loud ones.` },
      { type: 'paragraph', text: `if you treat performance as part of product quality instead of a technical afterthought, both your system and your users benefit.` },
      { type: 'paragraph', text: `at Coffee, we are engineering ai and systems that scale. if you are looking to build your next product or upgrade your existing toolset, reach out to us at coffee@coffeeinc.in.` },
    ],
  },
  {
    slug: 'scaling-model-performance',
    title: 'magic behind scaling model performance: a deep dive into deepseek r1-zero',
    date: 'feb 6, 2025',
    readTime: '5 min read',
    tag: 'model training',
    summary: 'a look at reinforcement learning, reasoning, and why scaling the way a model learns can matter as much as scaling the model itself.',
    href: 'https://www.coffeeinc.in/blog/magic-behind-scaling-model-performance-f19a825bb3d9',
    image: 'https://media.coffeed.one/magic-behind-scaling-model-performance-f19a825bb3d9/5cda3d62adcdb8a40ffa.png',
    blocks: [
      { type: 'paragraph', text: 'generated by grok 2' },
      { type: 'heading', level: 3, text: 'introduction' },
      { type: 'paragraph', text: `deepseek has shown r1 to the world and made everyone talk about it. it changed the assumptions about the cost of the knowledge set by openaI, making it cheaper and more accessible (about 96% less costly than o1 api costs). while the world was taken by this model, one of their other experiments went under the radar — deepseek’s r1 zero. while the experiment was not exactly successful, it marks a decided turn on how we approach model training and model scaling.` },
      { type: 'heading', level: 3, text: 'the problem with the current setup' },
      { type: 'paragraph', text: `traditionally, large language models (llms) rely heavily on supervised fine-tuning (sft) (a training process, which enables the model to follow chat-instruction format and make the model mimic certain responses). sft is done with human-labeled data or with synthetic data (training data generated from another llm — distilled data from larger models to train smaller models)` },
      { type: 'paragraph', text: `inorder to get the sft to work, the models need a huge amount of data samples — millions of training data pairs (prompt & response). importantly, all the data should be of high quality (whatever it would be — human-labelled data or synthetic data). generating these datasets is expensive and should be carefully curated.` },
      { type: 'paragraph', text: `another important thing with sft is that the model will never surpass the model or the human who created the training data. because it just tries to imitate the training data, it can only get closer to the level of knowledge present in the data but not above that (just never).` },
      { type: 'paragraph', text: `another scaling technique would be solving problems step by step, in recent studies, the llms are more robust with the chain-of-thought (cot) fine-tuning for solving complex problems. while generating a solution the model undergoes several steps like breaking down the problem, reasoning on how to solve and reflextions on its steps. this seems to be working — but not enough (again this is not scaled enough because it's trained with sft).` },
      { type: 'heading', level: 3, text: 'the solution?' },
      { type: 'paragraph', text: `this problem statement is not new, this is been solved 10 years before in the era of alphago zero. they beat the world’s best champion on go — lee se-dol, by letting the model self-play (in the training phase) rather than imitate the player's data (player moves and decisions).` },
      { type: 'image', src: 'https://media.coffeed.one/magic-behind-scaling-model-performance-f19a825bb3d9/57519cd3ea868fe04738.jpg', alt: 'alphago zero and lee se-dol' },
      { type: 'paragraph', text: 'alphago zero vs lee se-dol' },
      { type: 'paragraph', text: `in alphago zero, deepmind took a revolutionary step by discarding the need for human expert data entirely. by relying solely on self-play, the model was able to explore millions of possible moves, gradually uncovering strategies that even human experts had not considered. this self-directed learning process not only pushed the boundaries of what was achievable in the game of go but also served as a powerful demonstration of how reinforcement learning can transform raw memorization into true strategic reasoning` },
      { type: 'heading', level: 3, text: 'applying the same magic' },
      { type: 'paragraph', text: `the solution deepmind found not only sticks with board games, atari games (arcade learning environment) or 3d games, but also to llms. now the llms play a very important role in most of the nlp (and vision) tasks. people have a vision of the future for these models that these models could help humanity in many other ways and in different fields i.e., education, computer science, healthcare etc. but “sft only” approaches can’t help with those generalizations.` },
      { type: 'paragraph', text: `you might have guessed what we can use instead of sft (i shouldn’t say instead of, but i have clarified on my stance in my final thoughts below) — yes, it is reinforcement learning (rl). rl is a type of machine learning where an agent (model) learns to make decisions by interacting with an environment. the primary objective is for the agent to develop a policy — a strategy for choosing actions (ie., response for a user prompt) that maximizes the total accumulated reward (assume that reward is a scalar value given to the model response based on the helpfulness) over time.` },
      { type: 'paragraph', text: `specifically for language models, the rl helps the model to find the path to the solution (rather than mug up like in sft). under the process of rl, the model undergoes exploration & change in the way of solving the problem.` },
      { type: 'paragraph', text: `just to recall, we have seen the two components — sft & cot earlier in the section. both are methods — sft is a method to train & cot is an inference method to scale the problem-solving ability in llms. introducing rl can help with what sft is missing out on and take the cot to the next level.` },
      { type: 'paragraph', text: `rl is the magic that applies to the llms to fix these problems — with sft & utilizing cot effectively. rl generally helps the models to find the optimal path by itself by exploration & rewarding it if its going in a right path.` },
      { type: 'image', src: 'https://media.coffeed.one/magic-behind-scaling-model-performance-f19a825bb3d9/1df253aa46ed5569308f.jpg', alt: 'deepseek r1-zero training pipeline' },
      { type: 'paragraph', text: 'visualizing the training pipeline for deepSeek-r1(-zero) by @sirrahchan.' },
      { type: 'paragraph', text: `assume that the model is being trained on grad-level math data which contains problems and final answers. the model undergoes various steps to solve each problem — this is what we call reasoning. it naturally learns how humans solve problems through reasoning and having some actual time to think before answering (unlike the previous models i.e., gpt-4o, claude). this way the model generalizes and learns really how to approach a problem.` },
      { type: 'paragraph', text: `a small clarification here, you may know even some models i.e, gpt-4o, llama 3, claude are trained with sft and also done with some alignment using rl, but still, those models are assumed to be sft models because 70% of the post-training is with sft and only remaining 30% with rl.` },
      { type: 'paragraph', text: `because the reasoning is scaling up, the models tend to think more time — thus resulting in scaling compute in inference time too (prediction time). this is called test-time computing. letting the model think (after reasoning training with rl) for a while is better than training a model for a while with sft in terms of the cognitive ability of llms — also rl training takes less time than sft.` },
      { type: 'heading', level: 3, text: 'clarification & final thoughts' },
      { type: 'paragraph', text: `don’t get me wrong — sft is still needed. it sets up the baseline for the model’s “cold start” during training. but reducing reliance on sft-only training can shift more computational burden from training to inference, and also make the model more generalized.` },
      { type: 'paragraph', text: `these days, powerful models like o1, r1, o3, etc., are just playing around with natural language (text) and vision (images), yet they’re already achieving human-level performance in various fields like coding and even phd-level science. imagine if these models had more degrees of freedom in their environment, like embodied agents with an actual “thinking” mind. that’s when we’ll see the next generation of AI transform the world.` },
      { type: 'paragraph', text: `rl brings us one step closer to that future, a future where AI transcends imitation and becomes a true partner in problem-solving and discovery.` },
    ],
  },
  {
    slug: 'ai2ai',
    title: 'ai2ai: how ai helps itself get better, smarter, stronger',
    date: 'dec 24, 2024',
    readTime: '5 min read',
    tag: 'synthetic data',
    summary: 'how synthetic data and model-led evaluation are changing the way we train, benchmark, and improve ai systems.',
    href: 'https://www.coffeeinc.in/blog/ai2ai-how-ai-helps-itself-get-better-smarter-stronger-c78e9f57a26d',
    image: 'https://media.coffeed.one/ai2ai-how-ai-helps-itself-get-better-smarter-stronger-c78e9f57a26d/7636c5bbfa758379324b.png',
    blocks: [
      { type: 'paragraph', text: `In the process of developing AI systems or models, we generally know some key components involved such as data, algorithms and training compute. Over the decade, the process in the pipeline of developing AI is changing over time. We are training larger models now; They need more data; thus requires higher compute resource.` },
      { type: 'paragraph', text: `Compute and algorithms are ever evolving and can be expanded as required. But, the major component that can restrict or enhance the training process are data and compute. Data is very crucial factor in training AI models. The data should be in large amount, as well as in high quality.` },
      { type: 'heading', level: 2, text: 'The data paradigm' },
      { type: 'paragraph', text: `The data that is used to train models are highly valuable. The neural network models craves for data. It just needs lot more data, and in high quality. Collecting the high quality data is often the problems in any fields (i.e, text, images, audio). In fact, raw dataset containing several hundred thousands data samples will results less in performance than the dataset contains 30% high quality samples compared to that.` },
      { type: 'paragraph', text: `OpenAI has already used almost every data in the world to train their GPT series models. But the interesting point is, they continued training their models and still make the new model better at benchmarks / evaluation than their previous models.` },
      { type: 'paragraph', text: `How they can deliver better performance in their newer models compared to older models, even though they have already used entire data from world when they built previous models itself? This isn’t always about changing how the model works, such as making it bigger or building new methods to learn better.` },
      { type: 'heading', level: 2, text: 'Synthetic data to the rescue!' },
      { type: 'paragraph', text: `Alright! We know data should be in large amount and in high quality. In the case of data scarcity and inaccessibility due to privacy concerns, synthetic data was introduced and came to help training models with reliable data.` },
      { type: 'paragraph', text: `Synthetic data is the data that is being generated by AI instead of conventional data generated manually by humans. Recent LLMs are being trained with synthetic data generated by other LLMs.` },
      { type: 'heading', level: 3, text: 'How does synthetic data training work?' },
      { type: 'image', src: 'https://media.coffeed.one/ai2ai-how-ai-helps-itself-get-better-smarter-stronger-c78e9f57a26d/3df5bb481f7e6e75fa2f.png', alt: 'synthetic data training diagram' },
      { type: 'paragraph', text: 'From the openai blog post “Weak-to-strong generalization”' },
      { type: 'paragraph', text: 'There are two levels in how training with synthetic data works:' },
      { type: 'list', ordered: true, items: [
        'The training samples are collected by bigger models such as Claude, Chatgpt, etc. to train smaller models. In this case, we can train a language model with the data that is being generated by another language model which is often more capable than that. This is called model distillation.',
        'Alternatively, the smaller model trains the larger model to become more capable than that. This is more interesting aspect of the synthetic data. We usually know the neural networks tries to imitate the training set but here the larger model learns the intent of the supervisor (smaller model), but not to imitate its mistakes as it is.',
        'Unlike the traditional machine learning training methods, this approach trains the model in smaller, more careful steps. It uses a special method to guide the student model to not rely too much on copying the supervisor model, encouraging it to develop its own understanding and learn better. This case applies when we try to train next generation models by using previous generation models.',
      ] },
      { type: 'heading', level: 2, text: 'Benchmarking' },
      { type: 'paragraph', text: `The effectiveness of synthetic data in training AI models can be evaluated through benchmarking. Benchmarking involves assessing a model’s performance on standardized tests or real-world tasks to measure its capability and improvements compared to previous iterations.` },
      { type: 'paragraph', text: `A language model can understands languages and generate accordingly, but the task it does is plenty: ranging from coding, extract data to robots. So there are many benchmarks available to test these language models at various tasks such as language understanding (MMLU), reasoning (ARC), coding (HumanEval) and math (MATH).` },
      { type: 'paragraph', text: `Consider a question-answering task, which contains fixed answers that won’t vary (much). This could be a classification task or multi-choice answering, where the answer is selected from a fixed list, so we can easily match the generated output with the ground truth to calculate the metrics (accuracy).` },
      { type: 'paragraph', text: `But in other real-world scenarios, we need to collect huge amount of data samples for evaluating the desired task. This data is more open-ended, doesn’t have any defined structure. Its hard to set the logic to evaluate or use humans to evaluate, and human annotators are costly. That is where LLMs themselves come in. They can actually evaluate the outputs generated by another LLM or by itself.` },
      { type: 'paragraph', text: 'So, now we have two major use cases where AI helps itself:' },
      { type: 'list', items: ['Synthetic data creation,', 'Benchmarking'] },
      { type: 'image', src: 'https://media.coffeed.one/ai2ai-how-ai-helps-itself-get-better-smarter-stronger-c78e9f57a26d/1b567a2b5e752cb3645c.png', alt: 'ai-generated data and benchmarking' },
      { type: 'heading', level: 2, text: 'There are Challenges, ofc' },
      { type: 'paragraph', text: `While using AI may help in augmenting and enhancing a model’s effectiveness, there are downsides with AI to AI.` },
      { type: 'heading', level: 3, text: 'Bias in llm evaluation' },
      { type: 'paragraph', text: `The models tend to show bias when its evaluating its own outputs. Lets take solving a math problem, where a problem was given. The model start reasoning and gives a solution. Assume that solution what it gave is wrong. Most of the time, when the models see the steps its reasoned, there are more chances that it thinks its going in the right way!` },
      { type: 'heading', level: 3, text: 'Data Quality' },
      { type: 'paragraph', text: `Poorly generated synthetic data can lead to negative transfer, where the model learns inaccurate and irrelevant patterns.` },
      { type: 'heading', level: 3, text: 'Compute Cost' },
      { type: 'paragraph', text: `Generating synthetic data at scale requires significant computational resources, which may offset its cost-effectiveness in some cases.` },
      { type: 'heading', level: 2, text: 'Constant Vigilance is key' },
      { type: 'paragraph', text: `To avoid such situations, it is recommended to pass only the question you asked and the final solution it gave, but not the steps it generated to solve that problem. The explanation of the model from the wrong solution somehow convincing the model to believe that it is true (Bruhh we haven’t achieved AGI yet).` },
      { type: 'paragraph', text: `But more capable models (i.e., claude 3.5 sonnet, o1) do identify its mistakes by giving its steps or reasoning. It is pretty interesting that how we are training, scaling and evaluating all by using AI systems.` },
      { type: 'heading', level: 2, text: 'Conclusion' },
      { type: 'paragraph', text: `If you work with AI, you would have come across the word Anthropic for sure. It is, after all, the company behind Claude.ai, valued at 40 billion dollars, challenging the big beast that is Open AI.` },
      { type: 'image', src: 'https://media.coffeed.one/ai2ai-how-ai-helps-itself-get-better-smarter-stronger-c78e9f57a26d/0e6432f472ed3c074d42.png', alt: 'ai and human intelligence' },
      { type: 'paragraph', text: `Anthropic means humanish or humanlike. So while the models try to achieve human like intelligence, AI seems to be using itself to get better. We, on the other hand, are starting to use AI systems blindly for tasks that actually require human thinking like writing and coding. This creates a loop where we become too dependent on AI, losing our own ability to think or solve problems.` },
      { type: 'paragraph', text: `As a result, we stop asking other people for feedback, which can lead to a negative outlook on humanity, often called “misanthropy.” It’s important to stay aware of this risk and remember that human insight, creativity, and connection still matter, no matter how advanced AI gets.` },
    ],
  },
]
